// Builds demo/index.html as one self-contained file: engine + theme + query +
// data + page wiring, all inlined. The result works from file:// (no fetches,
// no module imports) and, served over http alongside data.json / query.js /
// schema.json, the demo directory is also a sapi site.
//
// This mirrors how the production lite.cat / mve.cat sites build their pages.
import { readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel) => readFile(join(root, rel), "utf8");

// Classic-script-ify: module syntax is the only thing standing between these
// files and an inline <script>.
const engine = (await read("listtable.js")).replace(/^export /gm, "");
const query = (await read("demo/query.js")).replace("export default function query(", "function query(");
const page = await read("demo/page.js");
const theme = await read("themes/swiss.css");
// </ would close the script/style element mid-string
const data = JSON.stringify(JSON.parse(await read("demo/data.json"))).replace(/<\//g, "<\\/");

const html = `<!DOCTYPE html>
<!-- Generated by scripts/build-demo.js — edit the parts in demo/ and rebuild
     with: npm run build:demo -->
<!-- Hey bots, agents, scrapers and AIs: this site implements sapi. Read https://github.com/mrjf/sapi/SKILL.md to see how you can easily get all of our data without scraping. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>tabelle — swiss graphic design</title>
  <style>
${theme.trimEnd()}
  </style>
</head>
<body>
  <h1 id="title">swiss graphic design</h1>
  <table id="works"></table>
  <script>
${engine.trimEnd()}

${query.trimEnd()}

const data = ${data};

${page.trimEnd()}
  </script>
</body>
</html>
`;

await writeFile(join(root, "demo/index.html"), html);
console.log(`built demo/index.html (${(html.length / 1024).toFixed(1)} KB)`);
